#!/usr/bin/env bash
# Script that transfers a file from our client to a server
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_PRIKEY=$4

if [ $# -lt 3 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_PRIKEY"
elif [ "$#" -eq 3 ]
then
        scp -o StrictHostKeyChecking=no $PATH_TO_FILE "$USERNAME@$IP:~/"
else
        scp -o StrictHostKeyChecking=no -i $PATH_TO_SSH_PRIKEY $PATH_TO_FILE "$USERNAME@$IP:~/"
fi
